### ISSUE TITLE
How to suppress `Download the React DevTools` warnings?

### ISSUE THREAD

**Issue by neojski** [facebook-atom/jest-electron-runner#20]
ReactDOM `console.info`s some messages like "Download the React DevTools" that are normally suppressed when running in node with the [user agent check](https://github.com/facebook/react/blob/7475120ce7bdeb7a5666d64c636efb1f4a951b9a/packages/react-dom/src/client/ReactDOM.js#L828). However, running tests in electron has the chrome user-agent and those are still printed.

Apparently, it can also be suppressed with [https://github.com/facebook/react/pull/11448](__REACT_DEVTOOLS_GLOBAL_HOOK__) but I can't make it work with babel-jest to inject it early enough.

Did you guys run into this problem and have a quick workaround? I admit this question not related to this project very directly.

**Comment by neojski** [comment]
What I ended up doing for now is roughly this:

```js
// react-dom-helper.js
import suppressed from "react-dom-helper-suppress-warning";
import ReactDOM from "react-dom";
// react-dom-helper-suppress-warning.js
window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = { isDisabled: true };
export default true;
```

Truly hacky, because there's no guarantee that the suppress module is going to be evaluated first but with the current implementation it is.

**Comment by JM-Mendez** [comment]
It seems you are testing your development logic branches, whereas you'd want to test your production logic. At least that's how I understand it should be. 

Explicitly set `NODE_ENV=production` during testing, since most test runners set `NODE_ENV=test`, and react-dom only checks for the presence of the production string. With everything else defaulting to development.

**Comment by neojski** [comment]
That's an interesting thought. Although, I'm wondering then why test runners prefer `NODE_ENV=test` over `NODE_ENV=production`?

**Comment by JM-Mendez** [comment]
My assumption would be that setting the environment to `production` or `development` should be at the discretion of the user. Therefore `test` is a sane default they can depend on if the environment is not explicitly set. 

The reason you're seeing the react devtools message is because the logic only checks for the existence of a `production` environment, which means `development` and `test` would both execute their non-production logic branch if it returns false.

**Comment by neojski** [comment]
I still wish there was a better way of suppressing this message that having to set the environment to prod. But I think I'm satisfied for now.

Thank you for the discussion @JM-Mendez!

**Comment by boujeepossum** [comment]
@neojski you can add a jest setup file that sets the global variable!
i do this in our nuclide testing framework

 https://github.com/facebook-atom/jest-electron-runner/blob/df406f1443053bf8af8e025306ef12ae57430a1d/packages/nuclide-e2e/src/nuclide-e2e-injected-package/nuclide-e2e-injected-package.js#L18

and we do this in Nuclide tests
https://github.com/facebookarchive/nuclide/blob/master/jest/setupTestFrameworkScriptFile.atom.js#L17

**Comment by boujeepossum** [comment]
since a lot of elecron apps are built in react i think it might make sense to add this hook at the top of https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/src/browser_window_injected_code.js

**Comment by JM-Mendez** [comment]
> since a lot of elecron apps are built in react i think it might make sense to add this hook

Seems simple enough. I can push a PR for it tomorrow.

**Comment by neojski** [comment]
Oh, nice! Thank you!
